package rules;

import main.java.drools.project.*;
import drools.project.Measurement;
import drools.project.Measurement2;
import drools.project.Helper;
import drools.project.Pruebas;
import accumulate drools.project.TestAccumulateFunction accumulatesSet;
import java.util.HashSet;
import drools.project.Testcheck;
import java.time.LocalDateTime;
import java.util.concurrent.TimeUnit;


global java.util.Set pito;
global drools.project.Helper helper;


query queryPrueba5c()
	Measurement( id  == "pez");
	Testcheck(check())
end

// Fired the activation here
rule "Rule 1"
	no-loop
when
	Testcheck(setBefore(LocalDateTime.now()))
	queryPrueba5c()
	$test: Testcheck(setAfter( LocalDateTime.now()))
then
	// Before Match Fired began here.

	TimeUnit.SECONDS.sleep(10);
	System.out.println("Test2: XXXX");

	// After Match Fired began here.
end

// Fired the activation here
rule "Rule 2"
	no-loop
when
	Measurement(id=="foca")
then
	// Before Match Fired began here.
	System.out.println("Ingreso Foca");
	// After Match Fired began here.
end